<table id="historytab" align="center">
<tr>
    <td width="50%">キーワード</d>
    <td width="25%">予約日付</td>
    <td width="25%"> </td>
</tr>

<?php 
if ($this->orders) {
    foreach ($this->orders as $row) {
        $keyword = htmlentities($row['kword'], ENT_QUOTES, "UTF-8");
        $id = $row['historyid'];
        $time = str_replace(array("/", " ", ":", "-"), "", $row['registdt']);
        $status = $row["status"];
        
        echo   '<tr>'.
        	       '<td><a href="/history/archive/'.$time.'_'.$keyword.'">'.$keyword.'</a><span style="display:none;">'.
                        $row['historyid'].'</span><span style="display:none;">'.$time.'</span></td>'.
        	       '<td>'.$row["updatedt"].'</td>';
        
        if ($status == null) {
            echo '<td>処理待ち</td>';
        } else if ($status == 0) {
            echo '<td>処理中</td>';
        } else if ($status == 1) {
            echo
            '<td><a href="/keyword/csv/download?id='.$row["historyid"].'" >Download</a></td>';
        }
        
        echo '</tr>';
    };    
}
?>

</table>