
<p id="readtex">
<p id="readtex">
<br>
<font size="5">検索履歴一覧</font><br>
<br>
「グーグルサジェスト キーワード一括ＤＬツール」を利用した、キーワードの検索履歴一覧です。<br>
他のユーザーがどのようなキーワードで検索したのかがわかります。（キーワードをクリックすると検索結果のページも表示されます）<br>
自分が検索するキーワードを他の人に知られたくない場合は、<a href="http://www.gskw.net/set/">ご自身のホームページに当ツール</a>を設置して検索してください。 <br>
<br/>

<table id="historytab" align="center">
<tr>
    <td width="20%">検索日時</d>
    <td width="55%">キーワード</td>
    <td width="25%">サジェスト件数</td>
</tr>

<?php 
    foreach ($this->rlist as $row) {
    	$keyword = htmlentities($row['kword'], ENT_QUOTES, "UTF-8");
    	$time = str_replace(array("/", " ", ":", "-"), "", $row['registdt']);
        echo '<tr><td>'.$row['registdt'].'</td>'.
            '<td><a href="http://'.$_SERVER['HTTP_HOST'].'/history/archive/'.$time.'_'.$keyword.'">'.$keyword.'</a><span style="display:none;">'.
            $row['id'].'</span><span style="display:none;">'.$time.'</span></td>'.
            '<td>'.$row['rstcnt'].'件</td></tr>';
    };
?>

</table>

<br/>

<form id="pfrm" action="<?php echo $this->baseUrl(); ?>history/index" method="post">
</form>
<?php 
    echo $this->pageno;
?>

<form id="dfrm" action="<?php echo $this->baseUrl(); ?>history/archive/" method="post">
<input type="hidden" id="id" name="id" value=""/>
</form>


<div class="clear"></div>