<?php $model="keywordyt";?>
<html>
<head>
<meta charset="utf-8" />
<title>Youtube キーワード削除</title>
<style type="text/css">
#detail {
    border: 1px solid #b9b9b9;
    border-collapse:collapse;
    width:800px;
}
#detail th{
    color: #333;
    background-color: #eee;
    border: 1px solid #b9b9b9;
    padding:3px;
}
#detail td {
    padding:3px;
    background-color: #fff;
    border: 1px solid #b9b9b9;
}

.btn {
    background: -moz-linear-gradient(top,#09C 0%,#09C 50%,#069 50%,#069);
    background: -webkit-gradient(linear, left top, left bottom,from(#09C), color-stop(0.5,#09C), color-stop(0.5,#069),  to(#069));
    border: 1px solid #DDD;
    color: #FFF;
    width: 100px;
    padding: 5px 10;
    text-decoration: none;
}

</style>
</head>
<body>
<a href="http://azkw.net/menu.php">削除トップメニュー頁に戻る</a>
<h3>Youtube。この頁で、キーワードを削除します。</h3>

<a class="btn" href="/<?php echo $model;?>/index/display-delete">クリア</a><br/>

<br/><br/>
<div style="height:20px;color:blue;">
検索機能
<span style="margin-left:330px;color:red;">削除機能</span>
</div>

<table id="tab" border=1 cellspacing=0 cellpadding=0 style="border-color:#FFF5EE;">
<tr>
<td style="background-color: #F0F8FF;">
    キーワード：
</td>
<td style="background-color: #FFF5EE;width:300px;padding-left:10px;">
    <form action="/<?php echo $model;?>/index/display-delete" method="GET">
        <input type="text" id="keyword" name="keyword" style="width:200px;" value="<?php echo $this->keyword; ?>"/>
        <input type="submit" value="検索" />
    </form>
</td>

<td style="background-color: #F0F8FF;">
    キーワード：<br/>
    パスワード：
</td>
<td style="background-color: #FFF5EE;width:300px;padding-left:10px;" >
    <form action="/<?php echo $model;?>/index/delete" method="POST">
        <input type="text" name="keyword" style="width:180px;margin-top:5px;" value=""/><br/>
        <input type="password" name="password" style="width:180px;margin-top:3px;" value=""/>
        <input type="submit" value="削除" />
    </form>
</td>
</tr>
</table>


<br/><br/>
<span style="color:red;"><?php echo $this->msg;?></span>


<?php 
if($this->rlist != null){

    echo '<table id="detail">
                <tr>
                    <th width="20%">検索時刻</th>
                    <th width="35%">キーワード</th>
                    <th width="10%">件数</th>
                    <th width="35%">IP</th>
                </tr>';
    
    foreach ($this->rlist as $row) {
    	$keyword = htmlentities($row['kword'], ENT_QUOTES, "UTF-8");
    	$time = str_replace(array("/", " ", ":", "-"), "", $row['registdt']);
    	
        echo '<tr>'.
            '<td>'.$row['registdt'].'</td>'.
            '<td><a target="_blank" href="http://'.$_SERVER['HTTP_HOST'].'/history/archive/'.$time.'_'.$keyword.'">'.$keyword.'</a><span style="display:none;">'.
            $row['id'].'</span><span style="display:none;">'.$time.'</span></td>'.
            '<td>'.$row['rstcnt'].'件</td>'.
            '<td>'.$row['clientip'].'</td>'.
            '</tr>';
    };
    echo "</table>";
}    
?>


</body>
</html>
