
<div id="form" class="clearfix"><br>
<div id="f_txt">キーワード</div>

<div id="f01">

<form id="keywordFrm" name="form" method="get" action="<?php echo $this->baseUrl(); ?>keyword/delete/search">
<input id="registflg" type="hidden" name="registflg" value="1">
<label>
<input id="keyword" type="text" name="keyword" class="madow" value="<?php echo $this->layout()->keyword; ?>">
</label>
<input id="but" name="　　検　索　　" type="button" value="　　検　索　　" class="madoww">
<div id="bloading"></div>
</form>
</div>

</div><div class="clear"></div>

<script>

var cook;
var cStart, cEnd;
var cnt;

//cookieが使えるか確認
if (navigator.cookieEnabled)
{
  cook = document.cookie;
  cStart = cook.indexOf("20150825", 0);

  if (cStart == -1)
  {
    document.cookie="20150825";
    window.location.reload(false);
  }
}

</script>
