<h3>ログインしてください：</h3>
<div style="height:400px;" align="center">
<form action="<?php echo $this->baseUrl(); ?>keyword/delete">
<div style="float:left;text-align:right;width:150px;margin-top:30px;">
<div style="height:20px;">パスワード:</div><br/>
</div>
<div style="float:left;border-color:blue;margin-top:30px;width:260px;">
<input type="password" id="psd" name="psd" style="width:200px;height:25px;"/><br/>
</div>

<div style="clear:both;">
<input type="submit" style="width:60px;" value="ログイン">
</div>
</form> 
</div>