<p id="readtex">
<p id="readtex">
<a href="/keyword/delete">前のページに戻る</a><br/><br/>
<font size="5">削除リスト</font><br>
<button id="delbut">&nbsp;削除&nbsp;</button>

<br>
<div style="text-align:right;">
<button id="allChk">全選択</button>
<button id="allUnchk">全解除</button>
</div>
<br/>

<table id="historytab" align="center">
<tr>
    <td width="15%">検索日時</d>
    <td width="40%">キーワード</td>
    <td width="15%">サジェスト件数</td>
    <td width="25%">IP</td>
    <td width="5%">&nbsp;</td>
</tr>

<?php 
    foreach ($this->rlist as $row) {
    	$keyword = htmlentities($row['kword'], ENT_QUOTES, "UTF-8");
    	$time = str_replace(array("/", " ", ":", "-"), "", $row['registdt']);
        echo '<tr><td>'.$row['registdt'].'</td>'.
            '<td><a target="_blank" href="http://'.$_SERVER['HTTP_HOST'].'/history/archive/'.$time.'_'.$keyword.'">'.$keyword.'</a><span style="display:none;">'.
            $row['id'].'</span><span style="display:none;">'.$time.'</span></td>'.
            '<td>'.$row['rstcnt'].'件</td>'.
            '<td>'.$row['clientip'].'</td>'.
            '<td><input type="checkbox" value='.$row['id'].' /></td>'        
        	.'</tr>';
    };
?>

</table>

<br/>

<form id="delfrm" action="<?php echo $this->baseUrl(); ?>keyword/delete/delete" method="post">
<input type="hidden" name="idlist" id="idlist"/>
<input type="hidden" name="delKwd" id="delKwd" value="<?php echo $this->delKwd;?>" />
</form>

<form id="dfrm" action="<?php echo $this->baseUrl(); ?>history/archive/" method="post">
<input type="hidden" id="id" name="id" value=""/>
</form>
<div class="clear"></div>