<p id="readtex">『ヤフーサジェスト キーワード一括ＤＬツール』は、Yahoo! JAPANのサジェスト機能で表示されるキーワード候補を１回の操作で一度に表示させ、ｃｓｖでまとめてダウンロードできるツールです。<br>
 検索数が多い最新のキーワード調査や、ホームページのコンテンツ作成時のヒントなどにご利用ください。<br>

<div id="form" class="clearfix">
<div id="kakomi1">
<div id="f_txt">キーワード</div>
</div>

<div id="f01">
<div id="kakomi2">
<form id="keywordFrm" name="form1" method="post" action="<?php echo $this->baseUrl(); ?>result">
<input id="registflg" type="hidden" name="registflg" value="1">
<label>
<input id="keyword" type="text" name="keyword" class="madow" value="<?php echo $this->layout()->keyword; ?>">
</label>
<input id="but" name="　　検　索　　" type="button" value="　　検　索　　" class="madoww">
<div id="bloading"></div>
</form>
</div>

</div>
<br/>
</div>
<div class="clear"></div>

<!-- banner start -->
<!--PC用広告表示-->
<div id="pc-0304">
<table class="splinkbox">
<tr><th colspan="2">スポンサードリンク</th></tr>
<tr>
<td><script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- ヤフーサジェスト_300x250 -->
<ins class="adsbygoogle"
style="display:inline-block;width:300px;height:250px"
data-ad-client="ca-pub-0338168428759491"
data-ad-slot="6600507153"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script></td>
<td><!-- admax -->
<script src="https://adm.shinobi.jp/s/2c73bee4f73108856da0322c90745626"></script>
<!-- admax --></td>
</tr>
</table>
</div>
<!--PC用広告表示　ＥＮＤ-->

<!--タブレット用広告表示-->
<div id="tab-03">
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- ヤフーサジェスト_300x250 -->
<ins class="adsbygoogle"
style="display:inline-block;width:300px;height:250px"
data-ad-client="ca-pub-0338168428759491"
data-ad-slot="6600507153"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
</div>
<!--タブレット用広告表示　ＥＮＤ-->

<!--スマホ用広告表示-->
<div id="smp-03">
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- ヤフーサジェスト_300x250 -->
<ins class="adsbygoogle"
style="display:inline-block;width:300px;height:250px"
data-ad-client="ca-pub-0338168428759491"
data-ad-slot="6600507153"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
</div>
<!--スマホ用広告表示　ＥＮＤ-->

</section>

<!--2段目 レスポンシブ広告-->
<div id="all-rs">
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- ヤフーサジェスト_リンク広告_rwd -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-0338168428759491"
     data-ad-slot="6214378352"
     data-ad-format="link"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
</div>

<!-- banner start -->


<div id="list">

  <p>検索結果：<?php echo $this->layout()->rstCnt; ?> 件のキーワード候補が見つかりました。</p>

  <?php echo $this->indextab; ?> 

<p class="aiueobox-txt">  
※上記の青文字をクリックすると、該当のキーワードのブロックにジャンプします。<br/>  
※<img src="/img/add.png" alt="＋" style="vertical-align:top">マークのあるキーワードをクリックすると、さらにサジェスト候補が表示されます。
</p>
<br>

<p><font color="#ED1F27">[PR]</font> <a href="http://www.ad8.co.jp/sks/" onmouseover="color='#0000FF'" onmouseout="color='#111111'" target="_blank">サイト売買ならココ。相場より高い値段で査定。他の売買サイトとの比較OK。</a></p><br>


<div class="boxA">
<!-- 広告 -->
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<ins class="adsbygoogle"
     style="display:block"
     data-ad-format="autorelaxed"
     data-ad-client="ca-pub-0338168428759491"
     data-ad-slot="1920105154"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
</div>
<br>

<!-- formup banner start -->
<p class="all-01">
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- ヤフーサジェスト_rwd -->
<ins class="adsbygoogle"
style="display:block"
data-ad-client="ca-pub-0338168428759491"
data-ad-slot="5123773956"
data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
</p>
<!-- formup banner end -->
  
<form action="<?php echo $this->baseUrl(); ?>keywordya/keyword/get-Csv-File" method="post" id="csvFrm">
    <input type="hidden" id="csvdata" name="csvdata" />
    <input type="hidden" id="historyid" name="historyid" value="<?php echo $this->historyid;?>" />
        
    <div class="csv_div">

<?php if ($this->layout()->isValidIp) { ?>
      	<input name="　　検　索　　2" type="button" value="　csv取得(all)　" class="madoww4 csvprime" style="background-image: url(/img/bt_csv_vip.jpg);">
<?php } else { ?>
		<input name="　　検　索　　2" type="button" value="　csv取得　" class="madoww2 csvfree">
<?php } 
      if (isset($this->layout()->usertype) && $this->layout()->usertype == 1) { ?>
		<input name="　　検　索　　2" type="button" value="　csv取得(予約)　" class="madoww4 csvorder" style="color:white;background-image: url(/img/bt_csv_order.jpg);">
<?php } ?>

    	<p style="margin-top:10px;"><img src="/img/add.png" alt="＋" style="vertical-align:top"><a href="/csvall.pdf" target="_blank">の下層ワードのcsv取得方法</a></p>
    </div>
</form><br/>
<p>
<b>キーワード候補一覧</b> （キーワード：<?php echo $this->layout()->keyword; ?>）<br>

<br/><br/>

<div id="jQ-menu">
    <?php echo $this->sk;?>
</div>


</p>

<p></p>
<div class="csv_div">
<?php if ($this->layout()->isValidIp) { ?>
      	<input name="　　検　索　　2" type="button" value="　csv取得(all)　" class="madoww4 csvprime" style="background-image: url(/img/bt_csv_vip.jpg);">
<?php } else { ?>
		<input name="　　検　索　　2" type="button" value="　csv取得　" class="madoww2 csvfree">
<?php } 
      if (isset($this->layout()->usertype) && $this->layout()->usertype == 1) { ?>
		<input name="　　検　索　　2" type="button" value="　csv取得(予約)　" class="madoww4 csvorder" style="color:white;background-image: url(/img/bt_csv_order.jpg);">
<?php } ?>
	<p style="margin-top:10px;"><img src="/img/add.png" alt="＋" style="vertical-align:top"><a href="/csvall.pdf" target="_blank">の下層ワードのcsv取得方法</a></p>
</div>
</div>



