<div id="readtex">
<font size="5">検索履歴一覧</font><br>
<br>
「ヤフーサジェスト キーワード一括ＤＬツール」を利用した、キーワードの検索履歴一覧です。<br>
他のユーザーがどのようなキーワードで検索したのかがわかります。（キーワードをクリックすると検索結果のページも表示されます）<br>
自分が検索するキーワードを他の人に知られたくない場合は、<a href="../set/">ご自身のホームページに当ツール</a>を設置して検索してください。 <br>
<br>
<table border="0" align="center">
<tr>
	<td width="20%"><u>検索日時</u></td>
	<td width="45%"><u>キーワード</u></td>
	<?php if (Com_Util::isAdmin($this->usertype)) {  ?>
		<td width="20%"><u>IP</u></td>
	<?php }?>	
  	<td width="15%"><u>サジェスト数</u></td>
</tr>

<?php 
    foreach ($this->rlist as $row) {
    	$keyword = htmlentities($row['kword'], ENT_QUOTES, "UTF-8");
    	$time = str_replace(array("/", " ", ":", "-"), "", $row['registdt']);
    	$id = $row['id'];
    	
        echo '<tr><td>'.$row['registdt'].'</td>'.
            '<td><a href="/history/archive/'.$time.'_'.$keyword.'">'.$keyword.'</a><span style="display:none;">'.
            $row['id'].'</span><span style="display:none;">'.$time.'</span></td>';
            if (Com_Util::isAdmin($this->usertype)) {
                echo '<td>'.$row['clientip'].'</td>';
            }        
        echo '<td>'.$row['rstcnt'].'件</td></tr>';
    };
?>


</table>

</div>

<br/>

<form id="pfrm" action="<?php echo $this->baseUrl(); ?>history/index" method="post">
</form>
<?php 
    echo $this->pageno;
?>

<form id="dfrm" action="<?php echo $this->baseUrl(); ?>history/archive/" method="post">
<input type="hidden" id="id" name="id" value=""/>
</form>


<div class="clear"></div>