<style>
input{ width:140px; }
input[name=email] { width:200px; }
#regist{ width:80px; }
.title{ color:blue; }
</style>

<span style="color: red;"><?php echo $this->msg;?></span>
<form action="/keyword/user/regist" onsubmit="return check();" method="post">
<span class="title"><b>ユーザー情報登録：</b></span>
<table id="historytab" align="center">
<tr>
    <td width="20%">ID(必須)</d>
    <td width="20%">ユーザー名(必須)</td>
    <td width="27%">メール</td>
    <td width="20%">パスワード(必須)</td>
    <td width="13%"></td>
</tr>
<tr>
    <td><input type="text" id="id" name="id" value="<?php echo $this->id; ?>"/></td>
    <td><input type="text" id="name" name="name" value="<?php echo $this->name; ?>"/></td>
    <td><input type="text" id="email" name="email" value="<?php echo $this->email; ?>"/></td>
    <td><input type="text" id="password" name="password" value="<?php echo $this->password; ?>"/></td>
    
    <td><input type="submit" id="regist" value="登録"/></td>
</tr>
</table>
</form>
<br/><br/><br/>



<span class="title"><b>ユーザー情報更新：</b></span>
<table id="historytab" align="center">
<tr>
    <td width="20%">ID</td>
    <td width="20%">ユーザー名(必須)</td>
    <td width="27%">メール</td>
    <td width="20%">パスワード(必須)</td>
    <td width="13%"></td>
</tr>

<?php 
if ($this->users) {
    foreach ($this->users as $row) {
        
        $id = $row['id'];
        $name = htmlentities($row['name'], ENT_QUOTES, "UTF-8");
        $email = $row["email"];
        $password = $row["password"];
        
        echo   '<tr>'.
        	       '<td>'.$id.'</td>'.
        	       '<td><input type="text" name="name" value="'.$name.'"/></td>'.
        	       '<td><input type="text" name="email" value="'.$email.'"/></td>'.
        	       '<td><input type="text" name="password" value="'.$password.'"/></td>'.
        	       '<td><button name="updbtn" uid='.$id.' >更新</button>&nbsp;&nbsp;
                        <button name="delbtn" style="display:none;" uid='.$id.' >削除</button></td>'.
                '</tr>';
    };    
}
?>
</table>
<form id="frm" action="" method="post">
<input type="hidden" id="updid" name="updid"/>
<input type="hidden" id="updname" name="updname"/>
<input type="hidden" id="updemail" name="updemail"/>
<input type="hidden" id="updpassword" name="updpassword"/>
</form>

<script type="text/javascript">
function check() {
	if ($("#id").val() == "") {
		alert("IDを入力してください");
		return false;
	}
	if ($("#name").val() == "") {
		alert("ユーザー名を入力してください");
		return false;
	}
	if ($("#password").val() == "") {
		alert("パスワードを入力してください");
		return false;
	}
	return true;
}

$("button[name=delbtn]").click(function(){

	$("#updid").val($(this).attr("uid"));
	$("#frm").attr("action", "/keyword/user/delete");
	$("#frm").submit();
});

$("button[name=updbtn]").click(function(){

	$("#updid").val($(this).attr("uid"));

	var password = $(this).closest("tr").find("input[name='password']").val();
	if (password == "") {
		alert("パスワードを入力してください");
		return;
	}
	var name = $(this).closest("tr").find("input[name='name']").val();
	if (name == "") {
		alert("ユーザー名を入力してください");
		return;
	}
	
	$("#updname").val(name);
	$("#updemail").val($(this).closest("tr").find("input[name='email']").val());
	$("#updpassword").val(password);
	
	$("#frm").attr("action", "/keyword/user/update");
	$("#frm").submit();
});
</script>