<!DOCTYPE html>
<html lang="ja">
<!--///-->
<head>

<?php
$pgurl = @$_SERVER["REQUEST_URI"];
$pathname = explode("?",$pgurl);
$pathname = explode("/",$pathname[0]);
$pathname = $pathname[1];
$debug = strpos($pgurl,"debug=1") . "";
$spmode = false;

$ua = $_SERVER['HTTP_USER_AGENT'];
if ((strpos($ua, 'Android') !== false) && (strpos($ua, 'Mobile') !== false) || (strpos($ua, 'iPhone') !== false) || (strpos($ua, 'Windows Phone') !== false)) {
	$debug = 1;
}

if ( $debug != "" ) {
$spmode = true;
?>
	<meta name="viewport" content="width=320px,user-scalable=yes">
	<script type="text/javascript" src="/sp/common_sp.js" charaset="UTF-8"></script>
	<script type="text/javascript" src="/sp/index_sp.js" charaset="UTF-8"></script>
	<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<?php } ?>

<script	src="<?php echo $this->baseUrl(); ?>_library/jquery-1.9.1.js" language="javascript"></script>

<meta charset="utf-8" />
<title>Googleサジェスト検索結果履歴│<?php echo $this->layout()->keyword; ?>│<?php echo $this->layout()->date; ?></title>
<meta name="description" content="「グーグルサジェスト キーワード一括ダウンロードツール」を使用して検索した検索ワード（キーワード）の履歴を紹介しているページです。検索ワード：「<?php echo $this->layout()->keyword; ?>」、調査時刻（年月日時分秒）：「<?php echo $this->layout()->date; ?>」">
<meta name="keywords" content="<?php echo $this->layout()->keyword; ?>,Googleサジェスト,検索,履歴,<?php echo $this->layout()->date; ?>">
<link rel="stylesheet" href="/_css/styles.css?t=<?php echo time(); ?>" type="text/css" />
<!--[if IE]><script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-25096557-9', 'gskw.net');
  ga('send', 'pageview');

</script>

<style type="text/css">
	.tool {
		width: 85%;
		margin: 20px auto 20px;
		border-collapse: collapse;
		font-size: 90%;
		line-height: 1.6em;
		border: 1px solid #0167CC;
		border-radius: 5px;
	}
	.tool ul {
		margin-top: 0px;
		padding-left: 20px;
		list-style: none;
	}
	.tool caption {
		padding-top: 10px;
		padding-bottom: 10px;
		font-weight: bold;
		line-height: 1.5em;
		color: #000;
		background-color: #FEE299;
		border-bottom: 1px solid #0167CC;
		border-radius: 5px 5px 0 0;
	}
	.tool th {
		width: 395px;
		padding-top: 10px;
		text-align: left;
		padding-left: 20px;
	}
	.tool td {
		padding-top: 0px;
		padding-bottom: 10px;
	}
	.tool a {
		text-decoration: none;
	}
/*---toolレスポンシブ----*/
@media (min-width:481px) and (max-width:800px){
	.tool th {
		width: 50%;
	}
	.tool td {
		width: 50%;
	}
}
@media (max-width : 480px){
	.tool {
		width: 90%;
	}
	.tool th {
		width: 50%;
	}	
}
</style>
</head>

<body>
<div id="header" class="clearfix"><p>グーグルサジェストのキーワード候補をまとめてｃｓｖでダウンロードできるツール</p>
<div id="fav">

<div id="lefticon1"><a href="https://twitter.com/share" class="twitter-share-button" <?php if ($spmode){ echo 'data-count="vertical"' ; } ?> data-url="http://www.gskw.net/" data-text="グーグルサジェスト キーワード一括ＤＬツール">Tweet</a><script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script></div>

<div id="fb-root"></div><script>(function(d, s, id) {
var js, fjs = d.getElementsByTagName(s)[0];
if (d.getElementById(id)) return;
js = d.createElement(s); js.id = id;
js.src = "//connect.facebook.net/ja_JP/all.js#xfbml=1";
fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script><div class="fb-like" data-href="https://www.gskw.net/" data-send="false" data-layout="<?php if ($spmode){ echo 'box' ; } else { echo 'button'; } ?>_count" data-width="450" data-show-faces="true"></div>

<div id="lefticon2">　<a href="http://b.hatena.ne.jp/entry/http://www.gskw.net/" class="hatena-bookmark-button" data-hatena-bookmark-title="グーグルサジェスト キーワード一括ＤＬツール" data-hatena-bookmark-layout="simple-balloon" title="このエントリーをはてなブックマークに追加"><img src="http://b.st-hatena.com/images/entry-button/button-only.gif" alt="このエントリーをはてなブックマークに追加" width="20" height="20" style="border: none;" /></a><script type="text/javascript" src="http://b.st-hatena.com/js/bookmark_button.js" charset="utf-8" async="async"></script></div>

<div id="lefticon3"><script type="text/javascript" src="https://apis.google.com/js/plusone.js"></script><g:plusone<?php if ($spmode){ echo ' size="tall"' ; } ?>></g:plusone></div>

<div id="lefticon4">
<?php if (isset($this->layout()->usertype) && $this->layout()->usertype == 1) {
    echo "<a href='/keyword/index/logout'>ログアウト</a>";
} else {
    echo "<a href='/keyword/index/login'>ログイン</a>";
 } ?>
</div><!-- lefticon4 -->
</div><!-- end fav -->

</div>

<?php
if ( $spmode ) {
	/* SPのみ広告差し込み */
	if ( $pathname == "" ) {
	include '/home/ad8-ssl/www/gskw/sp/adscript/index_ad_1.txt';
	} else if ( $pathname == "result"){
	include '/home/ad8-ssl/www/gskw/sp/adscript/result_ad_1.txt';
	}
}

?>

<div id="wrapper">
<header>

<div style="float:right;color:blue;margin-top:0px;">
<?php if (isset($this->layout()->usertype) && $this->layout()->usertype == 1) { 
        $username = "こんにちは、<B>".$this->layout()->username."</B>　様　";
        echo $username;
} ?>
</div>


<a href="/" title="グーグルサジェスト キーワード一括ダウンロードツール"></a>

</header>
<h1><span class="txtclear">グーグルサジェスト キーワード一括ＤＬツールGoogle Suggest Keyword Package Download Tool</span></h1>
<section id="main">
<section id="content">


<?php echo $this->layout()->content; ?>

</section>
</section>

<?php
if ( $spmode ) {
	/* SPのみ広告差し込み */
	if ( $pathname == "" ) {
	include '/home/ad8-ssl/www/gskw/sp/adscript/index_ad_2.txt';
	} else if ( $pathname == "result"){
	include '/home/ad8-ssl/www/gskw/sp/adscript/result_ad_2.txt';
	}
}

?>



<div class="tool">
	<table>
		<caption>あなたにおススメの「サイト」＆「ツール」をご紹介</caption>
		<thead>
			<tr>
				<th>■SEO関連</th>
				<th>■キーワード関連</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>
					<ul>
						<li><a href="http://www.y-seo.net/" target="_blank">1回5000円or月額1000円からの「安いSEO対策サービス」</a></li>
						<li><script type="text/javascript" src="http://www.infotop.jp/click.js"></script>
<a href="http://www.web-f.net/seoplus/" onClick="return clickCount(130546, 15722);">たった43ページの本物ＳＥＯマニュアル</a></li>
						<li><script type="text/javascript" src="http://www.infotop.jp/click.js"></script>
<a href="http://az.ctwpromotion.net/aff-compass/lp/kjag1p798.html" onClick="return clickCount(130546, 65474);">アフィリエイター専用SEO分析ツール「COMPASS」</a></li>
						<li><script type="text/javascript" src="http://www.infotop.jp/click.js"></script>
<a href="http://www.seo-keni.jp/" onClick="return clickCount(130546, 2058);">SEOに強い戦略的テンプレート「賢威7」</a>
</li>
						<li><a href="http://www.seo10.net/" target="_blank">目標順位を選べる成果報酬型「SEOファースト」</a></li>
					</ul>
				</td>
				<td>
					<ul>
						<li><script type="text/javascript" src="http://www.infotop.jp/click.js"></script>
<a href="http://az.ctwpromotion.net/pandora2/infotop.html" onClick="return clickCount(130546, 63824);">5000本を突破したキーワードツールの決定版「Pandora2」</a></li>
						<li><script type="text/javascript" src="http://www.infotop.jp/click.js"></script>
<a href="http://zqdle.net/prek/" onClick="return clickCount(130546, 62391);">お宝キーワードの発掘は「プレシャスキーワード」</a></li>
						<li><script type="text/javascript" src="http://www.infotop.jp/click.js"></script>
<a href="http://keywordstrike.com/" onClick="return clickCount(130546, 62776);">キーワード選定マニュアル「キーワードストライク」</a></li>
						<li><script type="text/javascript" src="http://www.infotop.jp/click.js"></script>
<a href="http://az.ctwpromotion.net/amc/keyword/top.html" onClick="return clickCount(130546, 60881);">ライバル皆無キーワードを発掘「キーワードスカウターS」</a></li>
						<li><a href="http://www.kwkt.net/" target="_blank">検索結果をそのまま保存「キーワード検索結果登録ツール」</a></li>
					</ul>
				</td>
			</tr>
		</tbody>
	</table>
</div>

<footer>
<section id="footer-area">
<section id="footer-outer-block">
<aside class="footer-segment01"><a href="/what/"><span style="color:#003366;">Googleサジェストとは</span></a></aside>
<aside class="footer-segment02"><a href="/history/"><span style="color:#003366;">検索履歴</span></a></aside>
<aside class="footer-segment03"><a href="/set/" ><span style="color:#003366;">当ツールをサイトに設置</span></a></aside>
<aside class="footer-segment04"><a href="/link/"><span style="color:#003366;">リンクについて</span></a></aside>
<aside class="footer-segment05"><a href="/prof/"><span style="color:#003366;">運営者情報</span></a></aside>
<aside class="footer-segment06"><a href="/mail/" target="_blank"><span style="color:#003366;">お問い合わせ</span></a></aside>
<aside class="footer-segment07"><a href="/"><span style="color:#003366;">TOP</span></a></aside>
</section>
Copyright (C) 1st-MEDIA,inc. All Rights Reserved.
</section>
</footer>

</div>
<br>
<p align="center">

<?php if ( $spmode == false ) {
/* PC表示の場合のみ表示 */
?>
<!-- admax -->
<script src="http://adm.shinobi.jp/s/c30c21949fb127b9a960a72a395e48d9"></script>
<!-- admax --><br />
<script type="text/javascript" src="http://www.infotop.jp/click.js"></script>
<a href="http://az.ctwpromotion.net/pandora2/infotop.html" onClick="return clickCount(130546, 63824);">一番売れているキーワードツール！ライバルが稼いでいるキーワードと商品一覧を合法的に「のぞき見」できます。</a>
	<br><br>
<?php } else {

/* SP表示の場合のみ広告タグ読み込み */
echo '<!--' . $pathname . '-->';
if ( $pathname == "" ) {
include '/home/ad8-ssl/www/gskw/sp/adscript/index_ad_3.txt';
} else if ( $pathname == "result"){
include '/home/ad8-ssl/www/gskw/sp/adscript/result_ad_3.txt';
}

} ?>

<div id="sidereadtex">
<!-- ---------------------------banner START  ---------------------------------- -->

<!-- geniee サイド追従枠 ここから left banner -->
<div id="g_floating_area1" style="display:none;top:0px;z-index:10000000000;right:50%;">

<!--  ad tags Size: 160x600 ZoneId:1033155-->
<script type="text/javascript" src="https://js.gsspcln.jp/t/033/155/a1033155.js"></script>

<!--  ad tags Size: 160x600 ZoneId:1084264-->
<!--<script type="text/javascript" src="//js.medi-8.net/t/084/264/a1084264.js"></script>-->
</div>

<!-- right banner -->
<div id="g_floating_area2" style="display:none;top:0px;z-index:10000000000;left:50%;">
<!--  ad tags Size: 160x600 ZoneId:1033156-->
<!--<script type="text/javascript" src="//107249.gsspcln.jp/t/033/156/a1033156.js"></script>-->

<script type="text/javascript" language="JavaScript">
   var ydn_id = '38807_132590';
</script>
<script type="text/javascript" language="JavaScript" src="//use-way-ad.com/usewaypc.js"></script>

</div>
<script type="text/javascript">                                                     
window.__gnsj = {
	    "contents_width": 900, //サイトのcontentsの幅に変換,
	    "extra_margin"  : 3,    //コンテンツから離したい幅に変換                        
	    "top_pos"       : 40,     //ページtopからの位置
	    "footer_pos"    : 0                               
};
</script>
<script type="text/javascript" src="//js.gsspcln.jp/sdk/l/geniee_sjv5.js"></script>
<!-- geniee サイド追従枠 ここまで -->

<!-- ---------------------------banner  END  ---------------------------------- -->
</div>

<script	src="<?php echo $this->baseUrl(); ?>_library/jMenu_new.js?date=20180211" language="javascript"></script>
<script	src="<?php echo $this->baseUrl(); ?>_library/spin.min.js" language="javascript"></script>
<script>
var clicked = "";
var opts = {
		  lines: 7, // The number of lines to draw
		  length: 5, // The length of each line
		  width: 5, // The line thickness
		  radius: 5, // The radius of the inner circle
		  corners: 0.3, // Corner roundness (0..1)
		  rotate: 0, // The rotation offset
		  direction: 1, // 1: clockwise, -1: counterclockwise
		  color: '#000', // #rgb or #rrggbb
		  speed: 1, // Rounds per second
		  trail: 60, // Afterglow percentage
		  shadow: false, // Whether to render a shadow
		  hwaccel: true, // Whether to use hardware acceleration
		  className: 'spinner', // The CSS class to assign to the spinner
		  zIndex: 2e9, // The z-index (defaults to 2000000000)
		  top: 'auto', // Top position relative to parent in px
		  left: 'auto' // Left position relative to parent in px
		};

var onFrmSubmit = function(){
	$("#bloading").css("display", "block");
	var target = document.getElementById('bloading');
	var spinner = new Spinner(opts).spin(target);	
 	return true;
}

$(function(){
	
	$("#but").click(function(){$("#keywordFrm").submit();});
	$("#keywordFrm").submit(onFrmSubmit);
	
	$("#jQ-menu").on("click", ".sugkey", function(){

	    var keyword = $(this).text();
	    var child = $(this).next();
	     
	    if(child.length > 0) {
	    	$(this).next().remove();
	    	return;
	    } else {
		    $(this).css("background", "url(<?php echo $this->baseUrl(); ?>_img/loading.gif) no-repeat right");
		    getSuggestKeywordAjax(keyword);		    
		    clicked = $(this);
	    }
	});
	
	$(".csvfree").click(function(){
		
		var csvdata = "";
		$(".til").each(function(){
			var title = $(this).find("span").text();
			$(this).next().children("li").each(function(){
				csvdata = csvdata + title + "," + $.trim($(this).children("span").text()) + "\n";
			});
		});	    
		$("#csvdata").val(csvdata);
		$("#csvFrm").submit();
	});	
	
	$(".csvprime").click(function(){
		
		var csvdata = "";
		$(".til").each(function(){
			var title = $(this).find("span").text();
			$ul = $(this).next('ul:eq(0)');
			if ($ul.length > 0 ) {
				csvdata += makeCsv(title, $ul);
			}
		});	    
		$("#csvdata").val(csvdata);
		$("#csvFrm").submit();
	});	

	$(".csvorder").click(function(){
		
		$.ajax({
			type: "post",
			url: "/keyword/keyword/get-Csv-File-Order",
			async: true,
			data:{"historyid" : $("#historyid").val()},
			success:function(data){
				alert(data);
			}
		}).responseText;		
	});	
	
	function makeCsv(path, $ul) {
		csv = '';
		$ul.children("li").each(function(){
			subpath = "";
			$(this).children().each(function(){
				if ($(this).prop("tagName") == "SPAN") {
					 
					subpath = $.trim($(this).text());
					csv += (path + "," + subpath + "\n");
					
				} else if ($(this).prop("tagName") == "UL") {
					
					csv += makeCsv(path + "," + subpath, $(this));
				}
			});
		});
		return csv;
	}

});

function getSuggestKeywordAjax(keyword){

	$.ajax({
		type: "post",
		url: "<?php echo $this->baseUrl(); ?>keyword/keyword/get-Suggest-Keyword-Ajax",
		async: true,
		data:{"keyword" : keyword},
		success:function(data){
			var rstNode = $(data);
			if(rstNode.children().length > 0){
			    clicked.after(rstNode);
			}
		    clicked.css("background-image", "");
		    clicked = null;
		}
	}).responseText;
}

</script>

<!--SP_下部固定（高さ50px）-->
<script type="text/javascript">
    var ydn_id = '43068_132594';
</script>
<script type="text/javascript" src="//use-way-ad.com/usewayfloat.js"></script>
<!--/SP_下部固定-->

</body>
</html>
