<!DOCTYPE html>
<html lang="ja">
<!--/-->
<head>
<meta charset="utf-8" />
<title>Googleサジェスト検索結果履歴│<?php echo $this->layout()->keyword; ?>│<?php echo $this->layout()->date; ?></title>
<meta name="description" content="「グーグルサジェスト キーワード一括ダウンロードツール」を使用して検索した検索ワード（キーワード）の履歴を紹介しているページです。検索ワード：「<?php echo $this->layout()->keyword; ?>」、調査時刻（年月日時分秒）：「<?php echo $this->layout()->date; ?>」">
<meta name="keywords" content="<?php echo $this->layout()->keyword; ?>,Googleサジェスト,検索,履歴,<?php echo $this->layout()->date; ?>">

<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>_css/styles.css?t=<?php echo time(); ?>" type="text/css" />
<!--[if IE]><script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-25096557-9', 'gskw.net');
  ga('send', 'pageview');

</script>

<style type="text/css">
	.tool {
		width: 85%;
		margin: 20px auto 20px;
		border-collapse: collapse;
		font-size: 90%;
		line-height: 1.6em;
		border: 1px solid #0167CC;
		border-radius: 5px;
	}
	.tool ul {
		margin-top: 0px;
		padding-left: 20px;
		list-style: none;
	}
	.tool caption {
		padding-top: 10px;
		padding-bottom: 10px;
		font-weight: bold;
		line-height: 1.5em;
		color: #000;
		background-color: #FEE299;
		border-bottom: 1px solid #0167CC;
		border-radius: 5px 5px 0 0;
	}
	.tool th {
		width: 395px;
		padding-top: 10px;
		text-align: left;
		padding-left: 20px;
	}
	.tool td {
		padding-top: 0px;
		padding-bottom: 10px;
	}
	.tool a {
		text-decoration: none;
	}
/*---toolレスポンシブ----*/
@media (min-width:481px) and (max-width:800px){
	.tool th {
		width: 50%;
	}
	.tool td {
		width: 50%;
	}
}
@media (max-width : 480px){
	.tool {
		width: 90%;
	}
	.tool th {
		width: 50%;
	}	
}
</style>
</head>

<body>
<div id="header" class="clearfix"><p>グーグルサジェストのキーワード候補をまとめてｃｓｖでダウンロードできるツール</p>
<div id="fav">

<div id="lefticon1"><a href="https://twitter.com/share" class="twitter-share-button" data-url="http://www.gskw.net/" data-text="グーグルサジェスト キーワード一括ＤＬツール">Tweet</a><script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script></div>

<div id="fb-root"></div><script>(function(d, s, id) {
var js, fjs = d.getElementsByTagName(s)[0];
if (d.getElementById(id)) return;
js = d.createElement(s); js.id = id;
js.src = "//connect.facebook.net/ja_JP/all.js#xfbml=1";
fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script><div class="fb-like" data-href="http://www.gskw.net/" data-send="false" data-layout="button_count" data-width="450" data-show-faces="true"></div>

<div id="lefticon2">　<a href="http://b.hatena.ne.jp/entry/http://www.gskw.net/" class="hatena-bookmark-button" data-hatena-bookmark-title="グーグルサジェスト キーワード一括ＤＬツール" data-hatena-bookmark-layout="simple-balloon" title="このエントリーをはてなブックマークに追加"><img src="http://b.st-hatena.com/images/entry-button/button-only.gif" alt="このエントリーをはてなブックマークに追加" width="20" height="20" style="border: none;" /></a><script type="text/javascript" src="http://b.st-hatena.com/js/bookmark_button.js" charset="utf-8" async="async"></script></div>

<div id="lefticon3"><script type="text/javascript" src="https://apis.google.com/js/plusone.js"></script><g:plusone></g:plusone></div>
</div>
</div>
<div id="wrapper">
<header><a href="/" title="グーグルサジェスト キーワード一括ダウンロードツール"></a></header>
<h1><span class="txtclear">グーグルサジェスト キーワード一括ＤＬツールGoogle Suggest Keyword Package Download Tool</span></h1>
<section id="main">
<section id="content">


<?php echo $this->layout()->content; ?>

</section>
</section>

<?php /*
<p align="center">
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- グーグルサジェスト キーワード一括ＤＬツール_728x15_ue -->
<ins class="adsbygoogle"
     style="display:inline-block;width:728px;height:15px"
     data-ad-client="ca-pub-0338168428759491"
     data-ad-slot="8881919553"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
<br><br>
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- グーグルサジェスト キーワード一括ＤＬツール_728x90 -->
<ins class="adsbygoogle"
     style="display:inline-block;width:728px;height:90px"
     data-ad-client="ca-pub-0338168428759491"
     data-ad-slot="9866019156"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
</p>
*/ ?>

<div class="tool">
	<table>
		<caption>あなたにおススメの「サイト」＆「ツール」をご紹介</caption>
		<thead>
			<tr>
				<th>■SEO関連</th>
				<th>■キーワード関連</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>
					<ul>
						<li><a href="http://www.y-seo.net/" target="_blank">1回5000円or月額1000円からの「安いSEO対策サービス」</a></li>
						<li><script type="text/javascript" src="http://www.infotop.jp/click.js"></script>
<a href="http://www.web-f.net/seoplus/" onClick="return clickCount(130546, 15722);">たった43ページの本物ＳＥＯマニュアル</a></li>
						<li><script type="text/javascript" src="http://www.infotop.jp/click.js"></script>
<a href="http://az.ctwpromotion.net/aff-compass/lp/kjag1p798.html" onClick="return clickCount(130546, 65474);">アフィリエイター専用SEO分析ツール「COMPASS」</a></li>
						<li><script type="text/javascript" src="http://www.infotop.jp/click.js"></script>
<a href="http://www.seo-keni.jp/" onClick="return clickCount(130546, 2058);">SEOに強い戦略的テンプレート「賢威7」</a>
</li>
						<li><a href="http://www.seo10.net/" target="_blank">目標順位を選べる成果報酬型「SEOファースト」</a></li>
					</ul>
				</td>
				<td>
					<ul>
						<li><script type="text/javascript" src="http://www.infotop.jp/click.js"></script>
<a href="http://az.ctwpromotion.net/pandora2/infotop.html" onClick="return clickCount(130546, 63824);">5000本を突破したキーワードツールの決定版「Pandora2」</a></li>
						<li><script type="text/javascript" src="http://www.infotop.jp/click.js"></script>
<a href="http://zqdle.net/prek/" onClick="return clickCount(130546, 62391);">お宝キーワードの発掘は「プレシャスキーワード」</a></li>
						<li><script type="text/javascript" src="http://www.infotop.jp/click.js"></script>
<a href="http://keywordstrike.com/" onClick="return clickCount(130546, 62776);">キーワード選定マニュアル「キーワードストライク」</a></li>
						<li><script type="text/javascript" src="http://www.infotop.jp/click.js"></script>
<a href="http://az.ctwpromotion.net/amc/keyword/top.html" onClick="return clickCount(130546, 60881);">ライバル皆無キーワードを発掘「キーワードスカウターS」</a></li>
						<li><a href="http://www.kwkt.net/" target="_blank">検索結果をそのまま保存「キーワード検索結果登録ツール」</a></li>
					</ul>
				</td>
			</tr>
		</tbody>
	</table>
</div>

<footer>
<section id="footer-area">
<section id="footer-outer-block">
<aside class="footer-segment01"><a href="http://www.gskw.net/what/"><span style="color:#003366;">Googleサジェストとは</span></a></aside>
<aside class="footer-segment02"><a href="http://www.gskw.net/history/"><span style="color:#003366;">検索履歴</span></a></aside>
<aside class="footer-segment03"><a href="http://www.gskw.net/set/" ><span style="color:#003366;">当ツールをサイトに設置</span></a></aside>
<aside class="footer-segment04"><a href="http://www.gskw.net/link/"><span style="color:#003366;">リンクについて</span></a></aside>
<aside class="footer-segment05"><a href="http://www.gskw.net/prof/"><span style="color:#003366;">運営者情報</span></a></aside>
<aside class="footer-segment06"><a href="http://www.gskw.net/mail/" target="_blank"><span style="color:#003366;">お問い合わせ</span></a></aside>
<aside class="footer-segment07"><a href="http://www.gskw.net/"><span style="color:#003366;">TOP</span></a></aside>
</section>
Copyright (C) 1st-MEDIA,inc. All Rights Reserved.
</section>
</footer>

</div>
<br>

<?php /*
<p align="center">
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- グーグルサジェスト キーワード一括ＤＬツール_728x90 -->
<ins class="adsbygoogle"
     style="display:inline-block;width:728px;height:90px"
     data-ad-client="ca-pub-0338168428759491"
     data-ad-slot="9866019156"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
<br><br>
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- グーグルサジェスト キーワード一括ＤＬツール_728x15_sita -->
<ins class="adsbygoogle"
     style="display:inline-block;width:728px;height:15px"
     data-ad-client="ca-pub-0338168428759491"
     data-ad-slot="1358652750"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
<br>
</p>
*/ ?>


<script	src="<?php echo $this->baseUrl(); ?>_library/jquery-1.9.1.js" language="javascript"></script>
<script	src="<?php echo $this->baseUrl(); ?>_library/jMenu.js" language="javascript"></script>
<script	src="<?php echo $this->baseUrl(); ?>_library/spin.min.js" language="javascript"></script>
<script>
var clicked = "";
var opts = {
		  lines: 7, // The number of lines to draw
		  length: 5, // The length of each line
		  width: 5, // The line thickness
		  radius: 5, // The radius of the inner circle
		  corners: 0.3, // Corner roundness (0..1)
		  rotate: 0, // The rotation offset
		  direction: 1, // 1: clockwise, -1: counterclockwise
		  color: '#000', // #rgb or #rrggbb
		  speed: 1, // Rounds per second
		  trail: 60, // Afterglow percentage
		  shadow: false, // Whether to render a shadow
		  hwaccel: true, // Whether to use hardware acceleration
		  className: 'spinner', // The CSS class to assign to the spinner
		  zIndex: 2e9, // The z-index (defaults to 2000000000)
		  top: 'auto', // Top position relative to parent in px
		  left: 'auto' // Left position relative to parent in px
		};

var onFrmSubmit = function(){
	$("#bloading").css("display", "block");
	var target = document.getElementById('bloading');
	var spinner = new Spinner(opts).spin(target);	
 	return true;
}

$(function(){
	
	$("#but").click(function(){$("#keywordFrm").submit();});
	$("#keywordFrm").submit(onFrmSubmit);
	
	$("#jQ-menu").on("click", ".sugkey", function(){
	    var keyword = $(this).text();
	    var child = $(this).next();
	     
	    if(child.length > 0) {
	    	$(this).next().remove();
	    	return;
	    } else {
		    $(this).css("background", "url(<?php echo $this->baseUrl(); ?>_img/loading.gif) no-repeat right");
		    getSuggestKeywordAjax(keyword);		    
		    clicked = $(this);
	    }
	});
	
	$(".csvfree").click(function(){
		
		var csvdata = "";
		$(".til").each(function(){
			var title = $(this).find("span").text();
			$(this).next().children("li").each(function(){
				csvdata = csvdata + title + "," + $.trim($(this).children("span").text()) + "\n";
			});
		});	    
		$("#csvdata").val(csvdata);
		$("#csvFrm").submit();
	});	
	
	$(".csvprime").click(function(){
		
		var csvdata = "";
		$(".til").each(function(){
			var title = $(this).find("span").text();
			$ul = $(this).next('ul:eq(0)');
			if ($ul.length > 0 ) {
				csvdata += makeCsv(title, $ul);
			}
		});	    
		$("#csvdata").val(csvdata);
		$("#csvFrm").submit();
	});	

	function makeCsv(path, $ul) {
		csv = '';
		$ul.children("li").each(function(){
			subpath = "";
			$(this).children().each(function(){
				if ($(this).prop("tagName") == "SPAN") {
					 
					subpath = $.trim($(this).text());
					csv += (path + "," + subpath + "\n");
					
				} else if ($(this).prop("tagName") == "UL") {
					
					csv += makeCsv(path + "," + subpath, $(this));
				}
			});
		});
		return csv;
	}

	$("#pageno").click(function(event){		
		if ($(event.target).is('a')){
			$("#currentNo").val($(event.target).find("span").text());
			var no = $(event.target).find("span").text();
			if (no == 1) no = "";
			var action = $("#pfrm").attr('action') + no + ".html";
			$("#pfrm").attr('action', action); 
			$("#pfrm").submit();
		}	
	});
	
	
});

function getSuggestKeywordAjax(keyword){

	$.ajax({
		type: "post",
		url: "<?php echo $this->baseUrl(); ?>keyword/keyword/get-Suggest-Keyword-Ajax",
		async: true,
		data:{"keyword" : keyword},
		success:function(data){
			var rstNode = $(data);
			if(rstNode.children().length > 0){
			    clicked.after(rstNode);
			}
		    clicked.css("background-image", "");
		    clicked = null;
		}
	}).responseText;
}

</script>

<!--SP_下部固定（高さ50px）-->
<script type="text/javascript" language="JavaScript">
    var ydn_id = '43068_132594';
</script>
<script type="text/javascript" language="JavaScript" src="//use-way-ad.com/usewayfloat.js"></script>
<!--/SP_下部固定-->

</body>
</html>
