<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta charset="utf-8" />
<title>Amazonサジェストから検索ワード候補を一括ダウンロード『アマゾンサジェスト キーワード一括ＤＬツール』</title>
<meta name="description" content="アマゾンのサジェスト機能を使用して、検索ワード候補を一覧表で表示させて、簡単にcsvで一括ダウンロードできるツールが『アマゾンサジェスト キーワード一括ＤＬツール』です。最新のキーワード調査やホームページのコンテンツ作成などにお役立てください。">
<meta name="keywords" content="Amazonサジェスト,キーワード,csv,一括,ダウンロード">
<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>_css/styles_az.css?ver=1" type="text/css" />
<meta name="viewport" content="width=device-width, user-scalable=yes, maximum-scale=1.0, minimum-scale=1.0">
<!--[if IE]><script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-25096557-14', 'auto');
  ga('send', 'pageview');

</script>

<style type="text/css">
	.tool {
		width: 85%;
		margin: 20px auto 30px;
		border-collapse: collapse;
		font-size: 90%;
		line-height: 1.6em;
		border: 1px solid #0167CC;
		border-radius: 5px;
	}
	.tool ul {
		margin-top: 0px;
		padding-left: 20px;
		list-style: none;
	}
	.tool caption {
		padding-top: 10px;
		padding-bottom: 7px;
		font-weight: bold;
		line-height: 1.5em;
		color: #000;
		background-color: #FEE299;
		border-bottom: 1px solid #0167CC;
		border-radius: 5px 5px 0 0;
	}
	.tool th {
		width: 395px;
		padding-top: 10px;
		text-align: left;
		padding-left: 20px;
	}
	.tool td {
		padding-top: 0px;
		padding-bottom: 10px;
	}
	.tool a {
		text-decoration: none;
	}
/*---toolレスポンシブ----*/
@media (min-width:481px) and (max-width:800px){
	.tool th {
		width: 50%;
	}
	.tool td {
		width: 50%;
	}
}
@media (max-width : 480px){
	.tool {
		width: 98%;
	}
	.tool th {
		width: 50%;
	}	
}
</style>

</head>
<body>
<div id="header" class="clearfix"><p>アマゾンサジェストのキーワード候補をまとめてｃｓｖでダウンロードできるツール</p>
<div id="fav">

<div id="lefticon1">
<div class="ninja_onebutton">
<script type="text/javascript">
//<![CDATA[
(function(d){
if(typeof(window.NINJA_CO_JP_ONETAG_BUTTON_14c6e7abe6aacc5e9c055784f841aff3)=='undefined'){
    document.write("<sc"+"ript type='text\/javascript' src='\/\/omt.shinobi.jp\/b\/14c6e7abe6aacc5e9c055784f841aff3'><\/sc"+"ript>");
}else{
    window.NINJA_CO_JP_ONETAG_BUTTON_14c6e7abe6aacc5e9c055784f841aff3.ONETAGButton_Load();}
})(document);
//]]>
</script><span class="ninja_onebutton_hidden" style="display:none;"></span><span style="display:none;" class="ninja_onebutton_hidden"></span>
</div>
</div><!-- lefticon1 -->

<div id="lefticon4">
<?php 
    if (Com_Util::isLoggedUser($this->layout()->usertype)) {
        echo "<a href='/keywordaz/index/logout'>ログアウト</a>";
    } else {
        echo "<a href='/keywordaz/index/login'>ログイン</a>";
    } ?>
</div><!-- lefticon4 -->

</div><!-- end fav -->

</div>

<div id="wrapper">

<?php if (Com_Util::isLoggedUser($this->layout()->usertype)) {
        echo '<div style="float:right;color:blue;margin-top:10px;">';

        $username = "こんにちは、<B>".$this->layout()->username."</B>　様　";
        echo $username;

        echo '<div id="csv-download" >CSV管理</div>';
        
        echo '</div>';

} ?>

<a href="/" title="アマゾンサジェスト キーワード一括ダウンロードツール">


	<img src="/_img_az/sitelogo.jpg" width="100%">
	

	
</a>

<h1><span class="txtclear">アマゾンサジェスト キーワード一括ＤＬツールamazon Suggest Keyword Package Download Tool</span></h1>
<section id="main">
<section id="content">


<?php echo $this->layout()->content; ?>

<div class="tool">
	<table>
		<caption>あなたにおススメの「サイト」＆「ツール」をご紹介</caption>
		<thead>
			<tr>
				<th>■SEO関連</th>
				<th>■キーワード関連</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>
					<ul>
						<li><a href="http://www.y-seo.net/" target="_blank">1回5000円or月額1000円からの「安いSEO対策サービス」</a></li>
						<li><script type="text/javascript" src="http://www.infotop.jp/click.js"></script>
<a href="http://www.web-f.net/seoplus/" onClick="return clickCount(130546, 15722);">たった43ページの本物ＳＥＯマニュアル</a></li>
						<li><script type="text/javascript" src="http://www.infotop.jp/click.js"></script>
<a href="http://az.ctwpromotion.net/aff-compass/lp/kjag1p798.html" onClick="return clickCount(130546, 65474);">アフィリエイター専用SEO分析ツール「COMPASS」</a></li>
						<li><script type="text/javascript" src="http://www.infotop.jp/click.js"></script>
<a href="http://www.seo-keni.jp/" onClick="return clickCount(130546, 2058);">SEOに強い戦略的テンプレート「賢威7」</a>
</li>
						<li><a href="http://www.seo10.net/" target="_blank">目標順位を選べる成果報酬型「SEOファースト」</a></li>
					</ul>
				</td>
				<td>
					<ul>
						<li><script type="text/javascript" src="http://www.infotop.jp/click.js"></script>
<a href="http://az.ctwpromotion.net/pandora2/infotop.html" onClick="return clickCount(130546, 63824);">5000本を突破したキーワードツールの決定版「Pandora2」</a></li>
						<li><script type="text/javascript" src="http://www.infotop.jp/click.js"></script>
<a href="http://zqdle.net/prek/" onClick="return clickCount(130546, 62391);">お宝キーワードの発掘は「プレシャスキーワード」</a></li>
						<li><script type="text/javascript" src="http://www.infotop.jp/click.js"></script>
<a href="http://keywordstrike.com/" onClick="return clickCount(130546, 62776);">キーワード選定マニュアル「キーワードストライク」</a></li>
						<li><script type="text/javascript" src="http://www.infotop.jp/click.js"></script>
<a href="http://az.ctwpromotion.net/amc/keyword/top.html" onClick="return clickCount(130546, 60881);">ライバル皆無キーワードを発掘「キーワードスカウターS」</a></li>
						<li><a href="http://www.kwkt.net/" target="_blank">検索結果をそのまま保存「キーワード検索結果登録ツール」</a></li>
					</ul>
				</td>
			</tr>
		</tbody>
	</table>
</div>


<div class="boxA">
<!-- 広告 -->
<p class="PRtitle">■あなたに旬なキーワードをご紹介</p>

<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- アマゾンサジェスト_関連コンテンツ_rwd -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-format="autorelaxed"
     data-ad-client="ca-pub-0338168428759491"
     data-ad-slot="2635634330"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
</div>


<p>[PR] <a href="http://www.akufoaddo.org/" target="_blank">看護師の転職をお考えの方の情報サイト</a></p>

</section>
</section>
<footer>
<section id="footer-area">
<section id="footer-outer-block" class="clearfix">
<aside class="footer-segment01"><a href="/what/">amazonサジェストとは</a></aside>
<aside class="footer-segment02"><a href="/history/">検索履歴</a></aside>
<aside class="footer-segment03"><a href="/set/" >当ツールをサイトに設置</a></aside>
<aside class="footer-segment04"><a href="/link/">リンクについて</a></aside>
<aside class="footer-segment05"><a href="/prof/">運営者情報</a></aside>
<aside class="footer-segment06"><a href="/mail/" target="_blank">お問い合わせ</a></aside>
<aside class="footer-segment07"><a href="/">TOP</a></aside>
</section>
Copyright (C) 1st-MEDIA,inc. All Rights Reserved.
</section>
</footer>
</div>

<br>

<!-- ---------------------------バナー  START  (footer down)---------------------------------- -->
<div id="all-rs">
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- アマゾンサジェスト_rwd -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-0338168428759491"
     data-ad-slot="3277696150"
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
</div>

<div id="all-rs">
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- アマゾンサジェスト_リンク広告_rwd -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-0338168428759491"
     data-ad-slot="9519670870"
     data-ad-format="link"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
</div>
<!-- ---------------------------バナー  END  (footer down)---------------------------------- -->

<br>

<script	src="<?php echo $this->baseUrl(); ?>_library/jquery-1.9.1.js" language="javascript"></script>
<script	src="<?php echo $this->baseUrl(); ?>_library/jMenu_new.js?ver=1" language="javascript"></script>
<script	src="<?php echo $this->baseUrl(); ?>_library/spin.min.js" language="javascript"></script>
<script>
var clicked = "";
var opts = {
		  lines: 7, // The number of lines to draw
		  length: 5, // The length of each line
		  width: 5, // The line thickness
		  radius: 5, // The radius of the inner circle
		  corners: 0.3, // Corner roundness (0..1)
		  rotate: 0, // The rotation offset
		  direction: 1, // 1: clockwise, -1: counterclockwise
		  color: '#000', // #rgb or #rrggbb
		  speed: 1, // Rounds per second
		  trail: 60, // Afterglow percentage
		  shadow: false, // Whether to render a shadow
		  hwaccel: true, // Whether to use hardware acceleration
		  className: 'spinner', // The CSS class to assign to the spinner
		  zIndex: 2e9, // The z-index (defaults to 2000000000)
		  top: 'auto', // Top position relative to parent in px
		  left: 'auto' // Left position relative to parent in px
		};

var onFrmSubmit = function(){

	if ( $("#keywordFrm").data("issubmit") != 1 ) {

		$("#but").attr("disabled", true);
		$("#keywordFrm").data("issubmit", 1);
		
		$("#bloading").css("display", "block");
		var target = document.getElementById('bloading');
		var spinner = new Spinner(opts).spin(target);
	 	return true;
	}
	return false;
}

$(function(){

	$("#but").click(function(){$("#keywordFrm").submit();});
	$("#keywordFrm").submit(onFrmSubmit);

	$("#csv-download").click(function(e){
		window.location.href = "/keywordaz/csv";
		e.stopPropagation();
	});

});

</script>
</body>
</html>
