<p id="readtex">『ビングサジェスト キーワード一括ＤＬツール』は、bingのサジェスト機能で表示されるキーワード候補を１回の操作で一度に表示させ、ｃｓｖでまとめてダウンロードできるツールです。<br>
検索数が多い最新のキーワード調査や、ホームページのコンテンツ作成時のヒントなどにご利用ください。</p>

<div id="form" class="clearfix">
<div id="kakomi1">
<div id="f_txt">キーワード</div>
</div>


<div id="f01">
<div id="kakomi2">
<form id="keywordFrm" name="form" method="post" action="<?php echo $this->baseUrl(); ?>result">
<input id="registflg" type="hidden" name="registflg" value="1">
<label>
<input id="keyword" type="text" name="keyword" class="madow" value="<?php echo $this->layout()->keyword; ?>">
</label>
</div>
<input id="but" name="　　検　索　　" type="button" value="　　検　索　　" class="madoww">
<div id="bloading"></div>
</form>
</div>

</div><div class="clear"></div>

<!--PC用広告表示-->
<div id="pc-0304">
<table class="splinkbox">
<tr><th colspan="2">スポンサードリンク</th></tr>
<tr>
<td><script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <!-- admax -->
		<script src="https://adm.shinobi.jp/o/75a7259fd9e318a5f8543306284dbe97"></script>
	<!-- admax -->
</td>
<td>
	<a href="http://www.y-seo.net/" target="_blank" rel="nofollow"><img src="https://www.bskw.net/img/yseo.png" alt="格安ＳＥＯ対策サービス"></a>
</td>
</tr>
</table>
</div>
<!--PC用広告表示　ＥＮＤ-->

<!--タブレット用広告表示-->
<div id="tab-03">
<!-- admax -->
<script src="https://adm.shinobi.jp/o/75a7259fd9e318a5f8543306284dbe97"></script>
<!-- admax -->
</div>
<!--タブレット用広告表示　ＥＮＤ-->

<!--スマホ用広告表示-->
<div id="smp-03">
<!-- admax -->
<script src="https://adm.shinobi.jp/o/75a7259fd9e318a5f8543306284dbe97"></script>
<!-- admax -->
</div>
<!--スマホ用広告表示　ＥＮＤ-->

</section>

<div id="all-02">

</div>


<div id="list">

  <p>検索結果：<?php echo $this->layout()->rstCnt; ?> 件のキーワード候補が見つかりました。</p>

  <?php echo $this->indextab; ?> 
  
<p class="aiueobox-txt">
※上記の青文字をクリックすると、該当のキーワードのブロックにジャンプします。<br/>
※<img src="/img/add.png" alt="＋" style="vertical-align:top">マークのあるキーワードをクリックすると、さらにサジェスト候補が表示されます。</p>
<br>

<p><font color="#ED1F27">[PR]</font> <a href="http://www.ad8.co.jp/sks/" onmouseover="color='#0000FF'" onmouseout="color='#111111'" target="_blank">サイトを売るならサイト買取サービスで。相場より高くサイト売買が可能です。</a></p>

<p class="all-01">

<!-- admax -->
<script src="https://adm.shinobi.jp/o/94dabf395814f2dd4e2548929c89f1d1"></script>
<!-- admax -->

</p>

<br>

<form action="<?php echo $this->baseUrl(); ?>keywordbs/keyword/get-Csv-File" method="post" id="csvFrm">
    <input type="hidden" id="csvdata" name="csvdata" />
    <input type="hidden" id="historyid" name="historyid" value="<?php echo $this->historyid;?>" />
    
    <div class="csv_div">

<?php if ($this->layout()->isValidIp) { ?>
      	<input name="　　検　索　　2" type="button" value="　csv取得(all)　" class="madoww4 csvprime" style="background-image: url(/img/bt_csv_vip.jpg);">
<?php } else { ?>
		<input name="　　検　索　　2" type="button" value="　csv取得　" class="madoww2 csvfree">
<?php } 
      if (Com_Util::isLoggedUser($this->layout()->usertype)) { ?>
		<input name="　　検　索　　2" type="button" value="　csv取得(予約)　" class="madoww4 csvorder" style="color:white;background-image: url(/img/bt_csv_order.jpg);">
<?php } ?>
    	
    	
    	<p style="margin-top:10px;"><img src="/img/add.png" alt="＋" style="vertical-align:top"><a href="/csvall.pdf" target="_blank">の下層ワードのcsv取得方法</a></p>
    </div>
</form><br/>
<p>
<b>キーワード候補一覧</b> （キーワード：<?php echo $this->layout()->keyword; ?>）<br>

<br/><br/>

<div id="jQ-menu">
    <?php echo $this->sk;?>
</div>


</p>

<div class="csv_div">

<?php if ($this->layout()->isValidIp) { ?>
      	<input name="　　検　索　　2" type="button" value="　csv取得(all)　" class="madoww4 csvprime" style="background-image: url(/img/bt_csv_vip.jpg);">
<?php } else { ?>
		<input name="　　検　索　　2" type="button" value="　csv取得　" class="madoww2 csvfree">
<?php } 
      if (Com_Util::isLoggedUser($this->layout()->usertype)) { ?>
		<input name="　　検　索　　2" type="button" value="　csv取得(予約)　" class="madoww4 csvorder" style="color:white;background-image: url(/img/bt_csv_order.jpg);">
<?php } ?>

	<p style="margin-top:10px;"><img src="/img/add.png" alt="＋" style="vertical-align:top"><a href="/csvall.pdf" target="_blank">の下層ワードのcsv取得方法</a></p>
</div>
</div>

